parameters:
   command_job_scheduler.class: Lilweb\JobBundle\Command\JobSchedulerCommand
   command_task_scheduler.class: Lilweb\JobBundle\Command\TaskSchedulerCommand

   job_resolver.class: Lilweb\JobBundle\Services\JobResolver
   task_scheduler.class: Lilweb\JobBundle\Services\TaskScheduler
   job_scheduler.class: Lilweb\JobBundle\Services\JobScheduler

   abstract_task.class: Lilweb\JobBundle\Services\AbstractTaskService

services:

    #
    # Les differents services.
    #

    lilweb.job_resolver:
        class: %job_resolver.class%
        arguments: [ "@logger", %lilweb_job_bundle.job_file% ]
        tags:
            - { name: monolog.logger, channel: jobs }


    lilweb.job_scheduler:
        class: %job_scheduler.class%
        arguments: [ "@logger", "@lilweb.job_resolver", "@doctrine.orm.entity_manager" ]
        tags:
            - { name: monolog.logger, channel: jobs }


    lilweb.task_scheduler:
        class: %task_scheduler.class%
        arguments: [ "@service_container", "@logger" ]
        tags:
            - { name: monolog.logger, channel: jobs }


    #
    # Les taches héritent de ce service.
    #

    lilweb.abstract_task:
        class: %abstract_task.class%
        abstract: true
        arguments: [ "@doctrine.orm.entity_manager", "@logger" ]
        tags:
            - { name: monolog.logger, channel: jobs }
